---
  development:
    AWS_ACCESS_KEY_ID: AKIAJNYAISQC7PQL5QLA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  test:
    AWS_ACCESS_KEY_ID: AKIAJNYAISQC7PQL5QLA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  production:
    AWS_ACCESS_KEY_ID: AKIAJNYAISQC7PQL5QLA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  