---
  development:
    AWS_ACCESS_KEY_ID: AKIAIM64SGK3YUI4TOIA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  test:
    AWS_ACCESS_KEY_ID: AKIAIM64SGK3YUI4TOIA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  production:
    AWS_ACCESS_KEY_ID: AKIAIM64SGK3YUI4TOIA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  