---
  development:
    AWS_ACCESS_KEY_ID: AKIAJNT56OQEYZXW7QAQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/818137434763/load_multiple_topics.fifo	
    P_QUEUE: load_multiple_topics.fifo
  test:
    AWS_ACCESS_KEY_ID: AKIAJNT56OQEYZXW7QAQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/818137434763/load_multiple_topics.fifo	
    P_QUEUE: load_multiple_topics.fifo