---
  development:
    AWS_ACCESS_KEY_ID: AKIAIKPM63YOURCOZXNQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/818137434763/load_multiple_topics.fifo	
    P_QUEUE: load_multiple_topics.fifo
  test:
    AWS_ACCESS_KEY_ID: AKIAIKPM63YOURCOZXNQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/818137434763/load_multiple_topics.fifo	
    P_QUEUE: load_multiple_topics.fifo
  production:
    AWS_ACCESS_KEY_ID: AKIAIKPM63YOURCOZXNQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/818137434763/load_multiple_topics.fifo	
    P_QUEUE: load_multiple_topics.fifo
  