---
  development:
    AWS_ACCESS_KEY_ID: AKIAJSHNXSCQEFWIX4WA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  test:
    AWS_ACCESS_KEY_ID: AKIAJSHNXSCQEFWIX4WA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  production:
    AWS_ACCESS_KEY_ID: AKIAJSHNXSCQEFWIX4WA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  