---
  development:
    AWS_ACCESS_KEY_ID: AKIAIOGLSX27XLPBFHLA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  test:
    AWS_ACCESS_KEY_ID: AKIAIOGLSX27XLPBFHLA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  production:
    AWS_ACCESS_KEY_ID: AKIAIOGLSX27XLPBFHLA
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: us-east-2
    P_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/628265443624/load_paragraphs.fifo	
    P_QUEUE: load_paragraphs.fifo
  